---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: release
  image: node:13
  commands:
  - yarn install
  - yarn build

- name: publish
  image: plugins/gh-pages
  settings:
    username:
      from_secret: username
    # password:
    #   from_secret: password
    user_name: appleboy
    user_email: appleboy.tw@gmail.com
    ssh_key:
      from_secret: ssh_key
    pages_directory: dist
