---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: release
  image: node:13
  environment:
    NODE_ENV: gh-pages
  commands:
  - yarn install
  - yarn build

- name: publish
  image: appleboy/gh-pages
  pull: always
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
    pages_directory: dist
    target_directory: 20213


- name: scp
  image: appleboy/drone-scp
  pull: always
  settings:
    host: 
      from_secret: dev_host
    port: 22
    username: 
      from_secret: dev_username
    password: 
      from_secret: dev_password
    target: /home/vue-manage-server
    source: .
    rm: true
    when:
      event: [push, pull_request]
      branch: [gh_pages]
